version: '3'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: fitgen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  postgres_data: