version: '3'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./:/var/www/html
    depends_on:
      - database-1.cpak6uiam1q1.eu-north-1.rds.amazonaws.com

  database-1.cpak6uiam1q1.eu-north-1.rds.amazonaws.com:
    image: postgres:14
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./plpgsql/fitgen_plpgsql_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./plpgsql/fitgen_plpgsql_triggers.sql:/docker-entrypoint-initdb.d/02-triggers.sql


volumes:
  postgres_data: